# Generated by Django 4.2.6 on 2024-09-22 07:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_card', models.CharField(max_length=200)),
                ('name_card', models.CharField(max_length=200)),
                ('cvv', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('accept', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JoinToGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('iin', models.CharField(max_length=200)),
                ('date_birth', models.DateField(blank=True, default=datetime.date.today)),
                ('phone_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('full_desc', models.TextField(blank=True)),
                ('mini_desc', models.CharField(blank=True, max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='media')),
                ('image', models.ImageField(blank=True, upload_to='upload')),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.language')),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
                ('child_navbars', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.navbar')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.language')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('full_desc', models.TextField(blank=True)),
                ('mini_desc', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='upload')),
                ('job', models.CharField(blank=True, max_length=200)),
                ('pdf', models.FileField(blank=True, upload_to='upload')),
                ('qr', models.CharField(blank=True, max_length=400)),
                ('status', models.IntegerField(default=0)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.language')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone1', models.CharField(max_length=200)),
                ('phone2', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
                ('instagram', models.CharField(max_length=200)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.language')),
            ],
        ),
    ]
